version: '3.8'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: result
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

networks:
  postgres-network:
